
name: Build Coq Reference Manual (ja)

on: [push, pull_request]

env:
  COQ_VER: v8.8.2

jobs:

  build_refman:
    name: build refman (ja)
    runs-on: ubuntu-18.04
    if: github.ref != 'refs/heads/gh-pages'
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          fetch-depth: 1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: ocaml/setup-ocaml@v1.1.12
        with:
          ocaml-version: 4.02.3

      - name: Install Camlp5
        run: |
          sudo apt-get install libstring-shellquote-perl
          eval $(opam env)
          opam install ocamlfind=1.9.1
          opam install camlp5=7.08

      - name: Install Sphinx
        run: |
          sudo apt-get install python3-pip gettext
          pip3 install sphinx
          pip3 install sphinx-rtd-theme
          pip3 install beautifulsoup4
          pip3 install pexpect
          pip3 install antlr4-python3-runtime
          pip3 install sphinxcontrib-bibtex

      - name: Install OmegaT
        run: |
          curl -SL https://jaist.dl.sourceforge.net/project/omegat/OmegaT%20-%20Standard/OmegaT%204.3.1/OmegaT_4.3.1_Linux_64.tar.bz2 | tar -jxf -

      - name: Build source po files
        run: |
          eval $(opam env)
          export PATH=$PATH:`python3 -m site --user-base`/bin
          make source
          make target OMEGAT=OmegaT_4.3.1_Linux_64/OmegaT.jar
          make html

      - uses: actions/upload-artifact@v1
        with:
          name: refman_ja
          path: html/refman

  publish_refman:
    name: publish refman(ja) to github pages
    runs-on: ubuntu-18.04
    needs: build_refman
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
        with:
          ref: gh-pages
          fetch-depth: 1

      - uses: actions/download-artifact@v1
        with:
          name: refman_ja

      - name: Commit refman
        run: |
          git config user.email "nephits@gmail.com"
          git config user.name "Github Action"
          git rm -rf refman/${COQ_VER}
          mv refman_ja refman/${COQ_VER}
          git add .
          if ! (git diff --quiet && git diff --staged --quiet); then
            git commit -m "Add: changes ($GITHUB_SHA)"
          fi

      - name: Push to gh-pages branch
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
        run: |
          git push https://eldesh:${PERSONAL_TOKEN}@github.com/eldesh/coq-refman-ja

