
name: Build Coq Reference Manual (ja)

on: [push, pull_request]

env:
  COQ_VER: v8.8.2

jobs:

  build_refman:
    name: build refman (ja)
    runs-on: ubuntu-18.04
    if: github.ref != 'refs/heads/gh-pages'
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          fetch-depth: 1

      - name: Set environment variables
        run: cat .env >> $GITHUB_ENV

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: ocaml/setup-ocaml@v1.1.12
        with:
          ocaml-version: ${{ env.OCAML_VERSION }}

      - name: Install OCaml packages
        run: |
          sudo apt-get install libstring-shellquote-perl
          eval $(opam env)
          opam pin add ocamlfind ${{ env.OCAMLFIND_VERSION }} --yes
          opam pin add camlp5 ${{ env.CAMLP5_VERSION }} --yes

      - name: Install Sphinx
        run: |
          sudo apt-get install python3-pip python3-setuptools gettext
          pip3 install wheel
          pip3 install -r context/requirements.txt

      - name: Cache OmegaT
        id: cache-omegat
        uses: actions/cache@v2
        with:
          key: cache-omegat-${{ env.OMEGAT_VERSION }}
          path: OmegaT_${{ env.OMEGAT_VERSION }}_Linux_64

      - name: Install OmegaT
        if: steps.cache-omegat.outputs.cache-hit != 'true'
        run: |
          curl -SL ${{ env.OMEGAT_URL }} | tar -jxf -

      - name: Build html documents
        run: |
          eval $(opam env)
          export PATH=$PATH:`python3 -m site --user-base`/bin
          make source
          make target OMEGAT=OmegaT_${{ env.OMEGAT_VERSION }}_Linux_64/OmegaT.jar
          make html

      - uses: actions/upload-artifact@v1
        with:
          name: refman_ja
          path: html/refman

  publish_refman:
    name: publish refman(ja) to github pages
    runs-on: ubuntu-18.04
    needs: build_refman
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
        with:
          ref: gh-pages
          fetch-depth: 1

      - uses: actions/download-artifact@v1
        with:
          name: refman_ja

      - name: Commit refman
        run: |
          git config user.email "nephits@gmail.com"
          git config user.name "Github Action"
          git rm -rf refman/${COQ_VER}
          mv refman_ja refman/${COQ_VER}
          git add .
          if ! (git diff --quiet && git diff --staged --quiet); then
            git commit -m "Add: changes ($GITHUB_SHA)"
          fi

      - name: Push to gh-pages branch
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
        run: |
          git push https://eldesh:${PERSONAL_TOKEN}@github.com/eldesh/coq-refman-ja

